const GREEN = '#d4d800';
const DARK_GRAY = '#404040';
const WHITE = '#ffffff';

export const dark = {
    dark: '1',
    PAGE_BG: DARK_GRAY,

    NAVIGATION_BG: GREEN,
    NAVIGATION_COLOR: DARK_GRAY,
    NAVIGATION_COLOR_HOVER: WHITE,

    ARTICLE_BORDER: WHITE,
    ARTICLE_COLOR: WHITE,
    ARTICLE_BG: 'transparent',

    ARTICLE_TITLE_HOVER: GREEN,

    ARTICLE_BUTTON_BG: GREEN,
    ARTICLE_BUTTON_COLOR: DARK_GRAY,
    ARTICLE_BUTTON_BORDER: GREEN,
    ARTICLE_BUTTON_BG_HOVER: 'transparent',
    ARTICLE_BUTTON_COLOR_HOVER: WHITE,
    ARTICLE_BUTTON_BORDER_HOVER: WHITE
};

export const light = {
    PAGE_BG: WHITE,

    NAVIGATION_BG: DARK_GRAY,
    NAVIGATION_COLOR: WHITE,
    NAVIGATION_COLOR_HOVER: GREEN,

    ARTICLE_BORDER: GREEN,
    ARTICLE_COLOR: DARK_GRAY,
    ARTICLE_BG: 'transparent',

    ARTICLE_TITLE_HOVER: GREEN,

    ARTICLE_BUTTON_BG: GREEN,
    ARTICLE_BUTTON_COLOR: DARK_GRAY,
    ARTICLE_BUTTON_BORDER: GREEN,
    ARTICLE_BUTTON_BG_HOVER: 'transparent',
    ARTICLE_BUTTON_COLOR_HOVER: DARK_GRAY,
    ARTICLE_BUTTON_BORDER_HOVER: DARK_GRAY
};
